const quotes = [
    "People tell you the world looks a certain way. Parents tell you how to think. Schools tell you how to think. TV. Religion. And then at a certain point, if you are lucky, you realize you can make up your own mind. Nobody sets the rules but you. You can design your own life. - Carrie Ann Moss",
    "Work hard daily.",
    "Success is built on consistency.",
    "Small progress is still progress.",
    "Some women choose to follow men, and some choose to follow their dreams. If youre wondering which way to go, remember that your career will never wake up and tell you that it doesnt love you anymore. - Lady Gaga",
    "the only way to do great work is to love what you do. - Steve Jobs",
    "people who are crazy enough to think they can change the world are the ones who do. - Steve Jobs",
    "The furture belongs to those who  believe in the beauty of the dream. - Eleanor Roosevelt",
    "never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe you can and you're halfway there. - Theodore Roosevelt",   
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "women belong in all places where decisions are being made. - Ruth Bader Ginsburg",
    "The most courageous act is still to think for yourself. Aloud. - Coco Chanel",
    "I am not afraid, I was born to do this. - Joan of Arc",
    "The question isn't who's going to let me; it's who is going to stop me. - Ayn Rand",
    "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
    "I am not free while any woman is unfree, even when her shackles are very different from my own. - Audre Lorde",

];

function newQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[randomIndex];
}